identifier: "Community.Games.Rust"
name: "Rust"
version: "1.0.0"
author: "TCAdmin"
shortDescription: "Rust"
longDescription: |
  # Rust
icon: "https://shared.fastly.steamstatic.com/community_assets/images/apps/252490/acf87ad23570b3c81f8c9cfc19544a07edd8b632.ico"
images:
  - "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/252490/ss_d0fdacaeef5a28a7cee525fd73376adfe083c964.1920x1080.jpg?t=1781536981"
tags:
  - "Game"
  - "Windows"
  - "Linux"
files:
  - path: "Rust - Windows.json"
    type: "GameConfig"
  - path: "Rust - Linux.json"
    type: "GameConfig"
