identifier: "Community.Games.HalfLifeCounterStrike16"
name: "Half Life - Counter-Strike 1.6"
version: "1.0.0"
author: "TCAdmin"
shortDescription: "Half Life - Counter-Strike 1.6"
longDescription: |
  # Half Life - Counter-Strike 1.6
icon: "https://shared.fastly.steamstatic.com/community_assets/images/apps/10/6b0312cda02f5f777efa2f3318c307ff9acafbb5.jpg"
images:
  - "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/10/0000000134.1920x1080.jpg?t=1745368572"
tags:
  - "Game"
  - "Windows"
  - "Linux"
files:
  - path: "CS - Windows.json"
    type: "GameConfig"
  - path: "CS - Linux.json"
    type: "GameConfig"
