identifier: "Community.Games.7DaystoDie"
name: "7 Days to Die"
version: "1.0.0"
author: "TCAdmin"
shortDescription: "7 Days to Die is an open-world game that is a unique combination of first-person shooter, survival horror, tower defense, and role-playing games. Play the definitive zombie survival sandbox RPG that came first. Navezgane awaits!"
longDescription: |
    # 7 Days to Die
    
    ## Description
      With over 20 million copies sold, 7 Days has defined the survival genre, with unrivaled crafting and world-building content. Set in a brutally unforgiving post-apocalyptic world overrun by the undead, 7 Days is an open-world game that is a unique combination of first-person shooter, survival horror, tower defense, and role-playing games. It presents combat, crafting, looting, mining, exploration, and character growth, in a way that has seen a rapturous response from fans worldwide. Play the definitive zombie survival sandbox RPG that came first. Navezgane awaits!
    
    ## Key Features
    - Console with RCON
    - Admin panel
    - Command lines
icon: "https://shared.akamai.steamstatic.com/community_assets/images/items/251570/ded9689fb5b30024eb3a5e116af058d939006141.png"
images:
  - "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/251570/header.jpg"
tags:
  - "Game"
  - "Windows"
  - "Linux"
files:
  - path: "7DTD - Windows.json"
    type: "GameConfig"
  - path: "7DTD - Linux.json"
    type: "GameConfig"
